/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reviewer_requiem_v2;

import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class addQuestionMenu extends EditorFrame {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JFrame addQuestionFrame;
    private javax.swing.JPanel TrueOrFalsePanel;
    private javax.swing.JTextField correctAnswerField;
    private javax.swing.JButton createIdentificationBtn;
    private javax.swing.JButton createMulChoiceButton;
    private javax.swing.JButton createTrueorFalseBtn;
    private javax.swing.JTextField iAnswerField;
    private javax.swing.JButton iCancelBtn;
    private javax.swing.JComboBox<String> iDiffSelector;
    private javax.swing.JTextField iHintField;
    private javax.swing.JTextField iQuestionField;
    private javax.swing.JPanel identificationPanel;
    private javax.swing.JButton mCancelBtn;
    private javax.swing.JComboBox<String> mDiffSelector;
    private javax.swing.JTextField mHintField;
    private javax.swing.JTextField mQuestionField;
    private javax.swing.JPanel multipleChoicePanel;
    private javax.swing.JTextField optionField1;
    private javax.swing.JTextField optionField2;
    private javax.swing.JTextField optionField3;
    private javax.swing.JScrollPane questionScrollField;
    private javax.swing.JScrollPane questionScrollField1;
    private javax.swing.JScrollPane questionScrollField3;
    private javax.swing.JTabbedPane questionTypeTabPane;
    private javax.swing.JButton tCancelBtn;
    private javax.swing.JComboBox<String> tDiffSelector;
    private javax.swing.JTextField tHintField;
    private javax.swing.JTextField tQuestionField;
    private javax.swing.JComboBox<String> trueOrFalseSelector;
    // End of variables declaration//GEN-END:variables
   
    /**
     * Creates new form addQuestionMenu
     */
    public addQuestionMenu() {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initComponents();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        

        addQuestionFrame = new JFrame();
        questionTypeTabPane = new javax.swing.JTabbedPane();
        identificationPanel = new javax.swing.JPanel();
        createIdentificationBtn = new javax.swing.JButton();
        javax.swing.JLabel iQuestionLbl = new javax.swing.JLabel();
        questionScrollField = new javax.swing.JScrollPane();
        iQuestionField = new javax.swing.JTextField();
        iAnswerField = new javax.swing.JTextField();
        iDiffSelector = new javax.swing.JComboBox<>();
        javax.swing.JLabel iDiffLbl = new javax.swing.JLabel();
        javax.swing.JLabel iAnswerLbl = new javax.swing.JLabel();
        javax.swing.JLabel iHintLbl = new javax.swing.JLabel();
        iHintField = new javax.swing.JTextField();
        iCancelBtn = new javax.swing.JButton();
        TrueOrFalsePanel = new javax.swing.JPanel();
        createTrueorFalseBtn = new javax.swing.JButton();
        javax.swing.JLabel tQuestionLbl = new javax.swing.JLabel();
        questionScrollField1 = new javax.swing.JScrollPane();
        tQuestionField = new javax.swing.JTextField();
        tDiffSelector = new javax.swing.JComboBox<>();
        javax.swing.JLabel tDiffLbl = new javax.swing.JLabel();
        javax.swing.JLabel tAnswerLbl = new javax.swing.JLabel();
        javax.swing.JLabel tHintLbl = new javax.swing.JLabel();
        tHintField = new javax.swing.JTextField();
        tCancelBtn = new javax.swing.JButton();
        trueOrFalseSelector = new javax.swing.JComboBox<>();
        multipleChoicePanel = new javax.swing.JPanel();
        createMulChoiceButton = new javax.swing.JButton();
        javax.swing.JLabel mQuestionLbl = new javax.swing.JLabel();
        questionScrollField3 = new javax.swing.JScrollPane();
        mQuestionField = new javax.swing.JTextField();
        correctAnswerField = new javax.swing.JTextField();
        mDiffSelector = new javax.swing.JComboBox<>();
        javax.swing.JLabel mDiffLbl = new javax.swing.JLabel();
        javax.swing.JLabel mAnswerLbl = new javax.swing.JLabel();
        javax.swing.JLabel mHintLbl = new javax.swing.JLabel();
        mHintField = new javax.swing.JTextField();
        mCancelBtn = new javax.swing.JButton();
        javax.swing.JLabel optionLbl1 = new javax.swing.JLabel();
        optionField1 = new javax.swing.JTextField();
        javax.swing.JLabel optionLbl2 = new javax.swing.JLabel();
        javax.swing.JLabel optionLbl3 = new javax.swing.JLabel();
        optionField2 = new javax.swing.JTextField();
        optionField3 = new javax.swing.JTextField();

        addQuestionFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addQuestionFrame.setTitle("Create a Question");
        addQuestionFrame.setResizable(false);
        addQuestionFrame.setVisible(true);

        createIdentificationBtn.setText("Create Question");
        createIdentificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createIdentificationBtnActionPerformed(evt);
            }
        });

        iQuestionLbl.setText("Question");

        iQuestionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iQuestionFieldActionPerformed(evt);
            }
        });
        questionScrollField.setViewportView(iQuestionField);

        iAnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAnswerFieldActionPerformed(evt);
            }
        });

        iDiffSelector.setMaximumRowCount(3);
        iDiffSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal", "Hard" }));
        iDiffSelector.setSelectedItem("Normal");
        iDiffSelector.setToolTipText("");
        iDiffSelector.setName(""); // NOI18N

        iDiffLbl.setText("Difficulty");

        iAnswerLbl.setText("Answer");

        iHintLbl.setText("Hint");

        iHintField.setText("Optional");
        iHintField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iHintFieldActionPerformed(evt);
            }
        });

        iCancelBtn.setText("Cancel");
        iCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout identificationPanelLayout = new javax.swing.GroupLayout(identificationPanel);
        identificationPanel.setLayout(identificationPanelLayout);
        identificationPanelLayout.setHorizontalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addComponent(iQuestionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionScrollField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iAnswerLbl)
                            .addComponent(iDiffLbl)
                            .addComponent(iHintLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iDiffSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iHintField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addComponent(iCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createIdentificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        identificationPanelLayout.setVerticalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identificationPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iQuestionLbl)
                    .addComponent(questionScrollField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iAnswerLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iHintLbl)
                    .addComponent(iHintField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iDiffSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iDiffLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iCancelBtn)
                    .addComponent(createIdentificationBtn)))
        );

        questionTypeTabPane.addTab("Identification", identificationPanel);

        createTrueorFalseBtn.setText("Create Question");
        createTrueorFalseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTrueorFalseBtnActionPerformed(evt);
            }
        });

        tQuestionLbl.setText("Question");

        tQuestionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tQuestionFieldActionPerformed(evt);
            }
        });
        questionScrollField1.setViewportView(tQuestionField);

        tDiffSelector.setMaximumRowCount(3);
        tDiffSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal", "Hard" }));
        tDiffSelector.setSelectedItem("Normal");
        tDiffSelector.setToolTipText("");
        tDiffSelector.setName(""); // NOI18N

        tDiffLbl.setText("Difficulty");

        tAnswerLbl.setText("Answer");

        tHintLbl.setText("Hint");

        tHintField.setText("Optional");
        tHintField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHintFieldActionPerformed(evt);
            }
        });

        tCancelBtn.setText("Cancel");
        tCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCancelBtnActionPerformed(evt);
            }
        });

        trueOrFalseSelector.setMaximumRowCount(3);
        trueOrFalseSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        trueOrFalseSelector.setToolTipText("");
        trueOrFalseSelector.setName(""); // NOI18N
        trueOrFalseSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueOrFalseSelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TrueOrFalsePanelLayout = new javax.swing.GroupLayout(TrueOrFalsePanel);
        TrueOrFalsePanel.setLayout(TrueOrFalsePanelLayout);
        TrueOrFalsePanelLayout.setHorizontalGroup(
            TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrueOrFalsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrueOrFalsePanelLayout.createSequentialGroup()
                        .addComponent(tQuestionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionScrollField1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TrueOrFalsePanelLayout.createSequentialGroup()
                        .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tAnswerLbl)
                            .addComponent(tDiffLbl)
                            .addComponent(tHintLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tDiffSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tHintField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trueOrFalseSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TrueOrFalsePanelLayout.createSequentialGroup()
                .addComponent(tCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createTrueorFalseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TrueOrFalsePanelLayout.setVerticalGroup(
            TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrueOrFalsePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tQuestionLbl)
                    .addComponent(questionScrollField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAnswerLbl)
                    .addComponent(trueOrFalseSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tHintLbl)
                    .addComponent(tHintField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDiffSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDiffLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(TrueOrFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tCancelBtn)
                    .addComponent(createTrueorFalseBtn)))
        );

        questionTypeTabPane.addTab("True or False", TrueOrFalsePanel);

        createMulChoiceButton.setText("Create Question");
        createMulChoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMulChoiceButtonActionPerformed(evt);
            }
        });

        mQuestionLbl.setText("Question");

        mQuestionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mQuestionFieldActionPerformed(evt);
            }
        });
        questionScrollField3.setViewportView(mQuestionField);

        correctAnswerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctAnswerFieldActionPerformed(evt);
            }
        });

        mDiffSelector.setMaximumRowCount(3);
        mDiffSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Normal", "Hard" }));
        mDiffSelector.setSelectedItem("Normal");
        mDiffSelector.setToolTipText("");
        mDiffSelector.setName(""); // NOI18N

        mDiffLbl.setText("Difficulty");

        mAnswerLbl.setText("Answer");

        mHintLbl.setText("Hint");

        mHintField.setText("Optional");
        mHintField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHintFieldActionPerformed(evt);
            }
        });

        mCancelBtn.setText("Cancel");
        mCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCancelBtnActionPerformed(evt);
            }
        });

        optionLbl1.setText("Option 1");

        optionLbl2.setText("Option 2");

        optionLbl3.setText("Option 3");

        javax.swing.GroupLayout multipleChoicePanelLayout = new javax.swing.GroupLayout(multipleChoicePanel);
        multipleChoicePanel.setLayout(multipleChoicePanelLayout);
        multipleChoicePanelLayout.setHorizontalGroup(
            multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleChoicePanelLayout.createSequentialGroup()
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multipleChoicePanelLayout.createSequentialGroup()
                        .addComponent(mCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createMulChoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(multipleChoicePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(multipleChoicePanelLayout.createSequentialGroup()
                                .addComponent(mQuestionLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(questionScrollField3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, multipleChoicePanelLayout.createSequentialGroup()
                                    .addComponent(mHintLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                    .addComponent(mHintField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, multipleChoicePanelLayout.createSequentialGroup()
                                    .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(optionLbl1)
                                        .addComponent(optionLbl2)
                                        .addComponent(optionLbl3)
                                        .addComponent(mAnswerLbl))
                                    .addGap(21, 21, 21)
                                    .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(correctAnswerField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(optionField1)
                                        .addComponent(optionField2)
                                        .addComponent(optionField3)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(multipleChoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mDiffLbl)
                .addGap(18, 18, 18)
                .addComponent(mDiffSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        multipleChoicePanelLayout.setVerticalGroup(
            multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multipleChoicePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mQuestionLbl)
                    .addComponent(questionScrollField3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAnswerLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionLbl1)
                    .addComponent(optionField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionLbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionLbl3))
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multipleChoicePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mHintField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multipleChoicePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mHintLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mDiffLbl)
                    .addComponent(mDiffSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(multipleChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCancelBtn)
                    .addComponent(createMulChoiceButton)))
        );

        questionTypeTabPane.addTab("Multiple Choice", multipleChoicePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(addQuestionFrame.getContentPane());
        addQuestionFrame.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionTypeTabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionTypeTabPane)
                .addContainerGap())
        );

        addQuestionFrame.pack();
        addQuestionFrame.setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCancelBtnActionPerformed
        addQuestionFrame.dispose();
    }//GEN-LAST:event_iCancelBtnActionPerformed

    private void iQuestionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iQuestionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iQuestionFieldActionPerformed

    private void iAnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iAnswerFieldActionPerformed

    private void iHintFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iHintFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iHintFieldActionPerformed

    private void createIdentificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createIdentificationBtnActionPerformed
        addQuestion("i");
    }//GEN-LAST:event_createIdentificationBtnActionPerformed

    private void createTrueorFalseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTrueorFalseBtnActionPerformed
        addQuestion("t");
    }//GEN-LAST:event_createTrueorFalseBtnActionPerformed

    private void tQuestionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tQuestionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tQuestionFieldActionPerformed

    private void tHintFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHintFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHintFieldActionPerformed

    private void tCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCancelBtnActionPerformed
        addQuestionFrame.dispose();
    }//GEN-LAST:event_tCancelBtnActionPerformed

    private void createMulChoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMulChoiceButtonActionPerformed
        addQuestion("m");
    }//GEN-LAST:event_createMulChoiceButtonActionPerformed

    private void mQuestionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mQuestionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mQuestionFieldActionPerformed

    private void correctAnswerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctAnswerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctAnswerFieldActionPerformed

    private void mHintFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHintFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mHintFieldActionPerformed

    private void mCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCancelBtnActionPerformed
        addQuestionFrame.dispose();
    }//GEN-LAST:event_mCancelBtnActionPerformed

    private void trueOrFalseSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueOrFalseSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueOrFalseSelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void addQuestion(String mode){
        Question newQuestion = new Question(0,"");
        String[] answers = {"","","",""};
        int id = setID(questionBank);
        if(mode.equalsIgnoreCase("i")){
            if(iQuestionField.getText().isEmpty() || iAnswerField.getText().isEmpty() || iHintField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "All fields must have value");
                return;
            }
            newQuestion = new Identification(id, iQuestionField.getText());
            answers[0] = iAnswerField.getText();
            newQuestion.setAnswer(answers);
            newQuestion.setHint(iHintField.getText());
            
            
        }else if(mode.equalsIgnoreCase("t")){
            if(tQuestionField.getText().isEmpty()|| tHintField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "All fields must have value");
                return;
            }
            newQuestion = new TrueOrFalse(id, tQuestionField.getText());
            answers[0] = trueOrFalseSelector.getSelectedItem().toString();
            newQuestion.setAnswer(answers);
            newQuestion.setHint(tHintField.getText());
            newQuestion.setDifficulty(tDiffSelector.getSelectedItem().toString());
            
        }else if(mode.equalsIgnoreCase("m")){
            if(mQuestionField.getText().isEmpty()|| mHintField.getText().isEmpty()|| correctAnswerField.getText().isEmpty()
                    || optionField1.getText().isEmpty()|| optionField2.getText().isEmpty()|| optionField3.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "All fields must have value");
                return;
            }
            newQuestion = new MultipleChoice(id, mQuestionField.getText());
            newQuestion.setAnswers(correctAnswerField.getText(), optionField1.getText(),optionField2.getText(),optionField3.getText());
            newQuestion.setHint(tHintField.getText());
            newQuestion.setDifficulty(tDiffSelector.getSelectedItem().toString());
        }
        
        JOptionPane.showMessageDialog(null, "<html>Question successfully created "+newQuestion.toString()+"</html>");
        questionBank.add(newQuestion);
        addQuestionFrame.dispose();
        new EditorFrame();
        
    }

    

}
