
package reviewer_requiem_v2;

public class ResultScreen extends javax.swing.JFrame {

    /**
     * Creates new form ResultScreen
     */
    public ResultScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultMainPanel = new javax.swing.JPanel();
        continueBtn = new javax.swing.JButton();
        challengeCompletedLbl = new javax.swing.JLabel();
        percentageLbl = new javax.swing.JLabel();
        ratingLbl = new javax.swing.JLabel();
        timeElapsed = new javax.swing.JLabel();
        correctAnswersLbl = new javax.swing.JLabel();
        scoreLbl = new javax.swing.JLabel();
        wrongAnswersLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        resultMainPanel.setBackground(new java.awt.Color(102, 102, 102));

        continueBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        continueBtn.setText("CONTINUE");
        continueBtn.setFocusable(false);

        challengeCompletedLbl.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        challengeCompletedLbl.setForeground(new java.awt.Color(255, 255, 0));
        challengeCompletedLbl.setText("CHALLENGE COMPLETED");

        percentageLbl.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        percentageLbl.setForeground(new java.awt.Color(255, 255, 204));
        percentageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentageLbl.setText("100%");

        ratingLbl.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ratingLbl.setForeground(new java.awt.Color(153, 255, 51));
        ratingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratingLbl.setText("EXCELLENT");

        timeElapsed.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        timeElapsed.setForeground(new java.awt.Color(255, 255, 255));
        timeElapsed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeElapsed.setText("04:45 seconds");

        correctAnswersLbl.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        correctAnswersLbl.setForeground(new java.awt.Color(255, 255, 255));
        correctAnswersLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correctAnswersLbl.setText("10 correct answers");

        scoreLbl.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        scoreLbl.setForeground(new java.awt.Color(0, 255, 255));
        scoreLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLbl.setText("10/10");

        wrongAnswersLbl.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        wrongAnswersLbl.setForeground(new java.awt.Color(255, 255, 255));
        wrongAnswersLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongAnswersLbl.setText("0 wrong answers");

        javax.swing.GroupLayout resultMainPanelLayout = new javax.swing.GroupLayout(resultMainPanel);
        resultMainPanel.setLayout(resultMainPanelLayout);
        resultMainPanelLayout.setHorizontalGroup(
            resultMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultMainPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(resultMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultMainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(resultMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(resultMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultMainPanelLayout.createSequentialGroup()
                                    .addComponent(challengeCompletedLbl)
                                    .addGap(65, 65, 65))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultMainPanelLayout.createSequentialGroup()
                                    .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(123, 123, 123)))))
                    .addGroup(resultMainPanelLayout.createSequentialGroup()
                        .addGroup(resultMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(resultMainPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(scoreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(timeElapsed, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correctAnswersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrongAnswersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        resultMainPanelLayout.setVerticalGroup(
            resultMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultMainPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(challengeCompletedLbl)
                .addGap(18, 18, 18)
                .addComponent(percentageLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ratingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(correctAnswersLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrongAnswersLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeElapsed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(continueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel challengeCompletedLbl;
    private javax.swing.JButton continueBtn;
    private javax.swing.JLabel correctAnswersLbl;
    private javax.swing.JLabel percentageLbl;
    private javax.swing.JLabel ratingLbl;
    private javax.swing.JPanel resultMainPanel;
    private javax.swing.JLabel scoreLbl;
    private javax.swing.JLabel timeElapsed;
    private javax.swing.JLabel wrongAnswersLbl;
    // End of variables declaration//GEN-END:variables
int resultPercentage;

}
